syavorsky/comment-parser

index.js
package.json
tests/files.spec.js

With virtually no changes, this PR makes this module (which is used by linters like `jscs`) work in node `0.8`, which I still support on as many of my modules as I can.
I'd consider this a semver-patch change, and if it's merged and released, I'll PR it into `node-jscs` as well.

Restore support for node 0.8 by using `readable-stream`

---

parser.js
tests/parse.js
tests/parse.spec.js

With `opts.join`
We can treat  non-star-start line as last part of previous line without a new `\n`
This may help if we need large same line string.
`opts.join` has 4 kinds of value we can choice:
* `true`: join previous line with a space
* `1`: join previous line with block intent
* `(string)`: join previous line with specified string
* `false` or `undefined`: do not join previous line
Could you gave me some advice for this PR?
Thank you!

add line not start with star join previous line options

---

README.md

It's not clear to everyone what causes `optional` to be true, so give an example. Also show `default` property.

Indicate when `optional` is `true`; `default` property

---

index.js
stringifier.js
tests/stringify.spec.js

This builds on #54 and #55 to provide a mechanism for converting (modified) parsed comment JSON back into a string. Supports indent.

Stringifier

---

README.md
stringifier.js
tests/stringify.spec.js

- Change: Add indent to start of block
- Fix: Ensure `stringifyBlocks`, `stringifyBlock`, and `stringifyTag` are exposed on `stringify`
- Fix: Avoid newlines with missing description
- Docs: Document `stringify` methods
Apologies, I have a few tweaks and docs here I should have added previously.
I think the indent at the start of the block is useful since the indent is generally one space less than the indent before each other line beginning with asterisks, and I think it is more convenient to handle this for the user.

Indent at start of block

---

index.d.ts

- Add comments for each interface and function. This help people when they consume this module as they can see the documenation inline and do not have to look it up online.
- Add options for the parser: "trim" and "join"
- Add the "stringify" function; as well as the "stringifyBlock", "stringifyBlocks", and "stringifyTag" functions
- Add properties on the parsed tag object: "default", "errors", and "tags"
- Rename the namespace from "CommentParser" to "parse", as per the official recommendations on a function module. Otherwise, it is not possible to export properties on the exported function.

Update type declaration file

---

parser.js
tests/parse.spec.js

This addresses an issue that came up for us at https://github.com/gajus/eslint-plugin-jsdoc/issues/443 .
I wouldn't think non-whitespace content should be auto-stripped, so this only skips a single space. (Let me know if you want it to strip tabs or other whitespace.)

fix: ensure non-space characters immediately after asterisk are included in source

---

stringifier.js
tests/stringify.spec.js

Previously, the asterisks on subsequent lines would be omitted - this preserves the property whereby `stringify(parse(str))` produces `str`.

fix: multiline descriptions

---

package.json
parser.js
tests/custom-parsers.spec.js
tests/parse.spec.js

- Refactoring: Remove unreachable code
- Testing: Bring coverage to 100%
- npm: Update devDeps
This doesn't require polluting the code to get to 100%. And it makes it easier to notice any future regressions in coverage.

Coverage and updates

---

parsers.js
tests/parse.spec.js

Fixes https://github.com/syavorsky/comment-parser/issues/83 and fixes https://github.com/syavorsky/comment-parser/issues/84 and fixes https://github.com/syavorsky/comment-parser/issues/86 .
This is a more comprehensive fix than https://github.com/syavorsky/comment-parser/pull/85 .

Name parsing fixes

---

parser.js
parsers.js
stringifier.js
tests/parse.spec.js
tests/stringify.spec.js

In looking at the change in #87 to preserve quotes, I took a look at the stringifier, and see if the stringifier should continue to work as is with the changes--and it does.
In fact, if that PR is not accepted for some reason, I see there is a preexisting problem with the stringifier too if an empty string default like `@param [someName='']` is given, as the stripping of quotes would cause the default value to become falsey and the default dropped entirely.
However, even if the PR is accepted (and I think it is a reasonable change), there is still the case that `* @param [name=]` would have the default dropped, and I think it would be more faithful to whatever intent the doc author had to ensure the stringifer doesn't drop even that.
This PR will thus fix either case.

- Preserve empty value for default

---

parser.js
tests/parse.spec.js

A user is in need of a marker start inside a jsdoc block: https://github.com/gajus/eslint-plugin-jsdoc/issues/568.
This PR adds such support.

- Fix: Allow `/**` within description

---

README.md
src/index.ts
src/stringifier/inspect.ts
tests/unit/inspect.spec.ts

adding helper for printing out tokens
```ts
import inspect from './stringifier/inspect'
inspect(parsed[0])
```
produces
```
|line|start|delimiter|postDelimiter|tag   |postTag|name |postName|type    |postType|description                     |end|
|----|-----|---------|-------------|------|-------|-----|--------|--------|--------|--------------------------------|---|
|   0|{2}  |/**      |             |      |       |     |        |        |        |                                |   |
|   1|{3}  |*        |{1}          |      |       |     |        |        |        |Description may go              |   |
|   2|{3}  |*        |{1}          |      |       |     |        |        |        |over few lines followed by @tags|   |
|   3|{3}  |*        |{1}          |@param|{1}    |name |{1} …
```

introduce inspect() helper

---

src/util.ts

I think this may have been a copy-paste error

docs: fix code comment

---

package-lock.json
package.json
tests/e2e/examples.spec.js
tests/e2e/issue-109.spec.js
tests/e2e/issue-112.spec.js
tests/e2e/issue-113.spec.js
tests/e2e/issue-119.spec.js
tests/e2e/issue-120.spec.js
tests/e2e/issue-121.spec.js
tests/e2e/issue-129.spec.js
tests/e2e/issue-41.spec.js
tests/e2e/issue-61.spec.js
tests/e2e/parse.spec.js
tests/e2e/stringify.spec.js
tests/e2e/transforms.spec.js

This is a fix for the beta channel, but one I think you are going to want to merge once confirmed it is working.
In my #130 PR, I had neglected to consider that the `exports` for CJS files needed to be `.cjs` given that with the change to `type: 'module'`, Node will interpret `.js` as ESM instead.
I also added `convert-extension`, a useful tool created because TypeScript has apparently insisted they will not be allowing control of output of extensions--as is needed for native ESM.
I also added an `--include=".js"` to the existing code to avoid converting paths within TypeScript files. I'm assuming those are safe to leave alone (if not required to be left alone).
Finally, I believe the tests were broken because `exports` will no longer find the `.cjs` extension. (In the future, I'd …

Fix CommonJS

---

package.json

Here's a separate PR you probably want. (We don't need it for a release ourselves as we've set the `engines`, but you might want to add it in a patch release, esp. with it coming so soon after--but whatever you want.)

bump `engines` per `exports` issues in earlier Node versions

---

package.json

Current (patched?) versions of Node should be reading `exports` in priority to `main`, but the older version of Node in Atom at least (12.14.1) does not seem to be doing so.
So although this bug should not have been impacting those using the correct version range, it would still be good to fix and have a release for.

fix: proper pointer for `main` in `package.json`

---

package.json

This reverts commit b11a8782c1c56ce2c9c84abc017f35edc526ade6.
For [issue141](https://github.com/syavorsky/comment-parser/issues/141).

Revert "bump `engines` per `exports` issues in earlier Node versions"

---

src/parser/index.ts
src/parser/source-parser.ts
src/parser/tokenizers/description.ts
src/primitives.ts
src/transforms/align.ts
tests/e2e/examples.js
tests/unit/source-parser.spec.ts

I know this is out of the blue, but I think this would be an awesome addition to the `comment-parser` package. 
**The problem**
The `comment-parser` package currently supports only JSDoc style comments, but it is capable of being language agnostic. 
The need for this appeared after I started using `sassdoc`, that relies on the following format:
```
////
/// This is a block description
/// @param value
////
```
Since it is supposed to support just about any `xdoc` markup, I thought that extending the functionality to provide the comment markers via options would make a huge difference.
**The solution**
- Added markers as options for the functions relying on markers
- Renamed the `Markers` enum to `DefaultMarkers`
- Added a new interface for `Markers`
- Added test for parsing with custom …

Added support for custom parser markers

---

src/parser/index.ts
tests/e2e/parse.spec.js
tests/unit/parser.spec.ts

I added the `\x20` markers at the end of line as my IDE does auto-trimming. Let me know if you need me to remove.

allow for valid empty jsdoc; fixes #128

---

.prettierignore
.prettierignore 

The `.prettierignore ` filename ends with a space, which is preventing me from checking out the repository (could be a Windows limitation).

 Removed trailing space from ".prettierignore " file name
